server:
  port: 8080
  mode: release  # 生产用 release

database:
  host: "127.0.0.1"        # 或 RDS 内网地址
  port: 5432
  user: ""
  password: ""             # 生产环境请使用环境变量: DB_PASSWORD
  dbname: ""

jwt:
  secret_key: ""            # 生产环境请使用环境变量: JWT_SECRET
  expire_hours: 24

wechat:
  app_id: ""           # 微信AppID
  app_secret: ""        # 公众号AppSecret，需要在微信公众平台获取
  mch_id: ""                   # 商户号
  api_v3_key: ""  # APIv3密钥
  serial_no: ""  # 证书序列号
  private_key_path: "/home/code/cert/apiclient_key.pem"  # 私钥文件路径
  notify_url: "https://iot4you.top/api/v1/payment/notify"  # 支付回调地址
